FROM node:20-alpine AS build
WORKDIR /app

COPY client/package.json client/yarn.lock ./

RUN yarn install --frozen-lockfile

COPY client/ .

RUN yarn build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
